"""
Build results/tables.md - every table for the report, generated from the CSVs (never typed by hand).

  1. Main comparison     methods x LOLv1 / LOLv2-real / LOLv2-syn: PSNR, SSIM, LPIPS
  2. Unpaired (NIQE)     LIME, DICM, MEF
  3. Ablation            fine-tuning runs A-D (+ the pretrained starting point)
  4. Detection           YOLOv8m mAP on ExDark (1,200 imgs, CPU) and the 200-image subset
  5. Efficiency          parameters and time per image on one Tesla T4

Best value per column in **bold** (higher PSNR/SSIM/mAP, lower LPIPS/NIQE/time).
Rows that are NOT fair comparisons (use ground-truth brightness, a checkpoint chosen on the test
set, or leaked test data) are listed under "reference only" and never bolded.

Usage:
    python scripts/make_tables.py
"""

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "results"

MAIN = ["Input", "HE", "CLAHE", "Gamma", "Zero-DCE", "SCI", "SNR-Aware (released)", "LLFormer", "GSAD",
        "Retinexformer", "Retinexformer (my training)"]
REFERENCE = {"GSAD (GT-mean, authors protocol)": "uses ground-truth brightness",
             "Retinexformer (my training; best-on-test ckpt)": "checkpoint chosen on the test set",
             "LLFormer [INVALID: test overlaps LOLv1 train]": "91/100 test images seen in training",
             "LLFormer (LOLv1 weights - cross-dataset)": "LOL-v1 weights on synthetic data"}
ABL = [("Retinexformer", "pretrained (start point)"), ("FT-A control (L1)", "A: L1 (control)"),
       ("FT-B SNR-L1 (mine)", "B: SNR-weighted L1 (mine)"), ("FT-C L1+FFT", "C: L1 + FFT"),
       ("FT-D SNR-L1+FFT", "D: SNR-L1 + FFT")]
ABL_DET = {"Retinexformer": "rf_pretrained_gpu_200gpu", "FT-A control (L1)": "ft_A_l1_200gpu",
           "FT-B SNR-L1 (mine)": "ft_B_snr_200gpu", "FT-C L1+FFT": "ft_C_fft_200gpu", "FT-D SNR-L1+FFT": "ft_D_snr_fft_200gpu"}
HIGHER = {"psnr": True, "ssim": True, "lpips": False, "niqe": False, "mAP50": True, "mAP50-95": True,
          "dark_psnr": True, "dark_ssim": True, "ms": False}


def load(name, key):
    p = R / name
    return {tuple(r[k] for k in key): r for r in csv.DictReader(open(p))} if p.exists() else {}


def num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def table(header, rows, kinds, fmt):
    """rows: [label, v1, v2, ...]; kinds[i] = metric kind of column i (or None) for bolding the best."""
    best = {}
    for j, k in enumerate(kinds):
        vals = [num(r[j + 1]) for r in rows if num(r[j + 1]) is not None]
        if k and vals:
            best[j] = max(vals) if HIGHER[k] else min(vals)
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    for r in rows:
        cells = [r[0]]
        for j, v in enumerate(r[1:]):
            x = num(v)
            s = "–" if x is None else fmt[j].format(x)
            if x is not None and j in best and abs(x - best[j]) < 1e-9:
                s = f"**{s}**"
            cells.append(s)
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def main():
    res = load("results.csv", ["method", "dataset"])
    dark = load("dark_region.csv", ["method", "dataset"])
    det = load("detection.csv", ["method"])
    speed = load("speed.csv", ["method"])
    out = ["# Results tables", "", "_Generated by `scripts/make_tables.py` from the CSVs in `results/` - do not edit by hand._", ""]

    # 1. main comparison
    sets = ["LOLv1", "LOLv2-real", "LOLv2-syn"]
    hdr = ["Method"] + [f"{d} {m}" for d in sets for m in ("PSNR↑", "SSIM↑", "LPIPS↓")]
    kinds = [k for _ in sets for k in ("psnr", "ssim", "lpips")]
    fmt = ["{:.2f}", "{:.3f}", "{:.3f}"] * 3
    # LOL-v1-only weights tested on synthetic LOLv2 are a cross-dataset result -> reference section, not main
    CROSS = {("Retinexformer (my training)", "LOLv2-syn")}
    rows = [[m] + [None if (m, d) in CROSS else res.get((m, d), {}).get(k) for d in sets for k in ("psnr", "ssim", "lpips")]
            for m in MAIN]
    out += ["## 1. Main comparison (paired test sets)", "",
            "Retinexformer and SNR-Aware use weights trained on each dataset; LLFormer has LOL-v1 weights only; "
            "Retinexformer (my training) was trained on LOL-v1 only (LOLv2-real omitted: 91/100 test images are LOL-v1 "
            "training images). SNR-Aware = results released by the authors.", "",
            table(hdr, rows, kinds, fmt), "", "**Reference only (not comparable, never bolded):**", ""]
    ref_rows = [[f"{m} — _{why}_"] + [res.get((m, d), {}).get(k) for d in sets for k in ("psnr", "ssim", "lpips")]
                for m, why in REFERENCE.items() if any((m, d) in res for d in sets)]
    for m, d in CROSS:
        if (m, d) in res:
            ref_rows.append([f"{m} — _LOL-v1 weights on synthetic data_"] +
                            [res[(m, d)][k] if dd == d else None for dd in sets for k in ("psnr", "ssim", "lpips")])
    out += [table(hdr, ref_rows, [None] * len(kinds), fmt), ""]

    # 2. unpaired NIQE
    up = ["LIME", "DICM", "MEF"]
    rows = [[m] + [res.get((m, d), {}).get("niqe") for d in up] for m in MAIN + [a for a, _ in ABL[1:]]
            if any(res.get((m, d), {}).get("niqe") for d in up)]
    out += ["## 2. Unpaired sets — NIQE (lower is better)", "",
            "Retinexformer and its fine-tuned versions use LOL-v1 weights here.", "",
            table(["Method"] + up, rows, ["niqe"] * 3, ["{:.3f}"] * 3), ""]

    # 3. ablation
    hdr = ["Run", "LOLv1 PSNR↑", "LOLv1 SSIM↑", "LOLv1 LPIPS↓", "dark-30% PSNR↑", "dark-30% SSIM↑",
           "LOLv2-syn PSNR↑", "NIQE mean↓", "ExDark-200 mAP50↑"]
    rows = []
    for m, label in ABL:
        n = [num(res.get((m, d), {}).get("niqe")) for d in up]
        # start point on LOLv2-syn: the SAME LOL-v1 weights (table 1's Retinexformer row uses LOLv2-syn-trained weights)
        syn = res.get(("Retinexformer (LOL-v1 weights)" if m == "Retinexformer" else m, "LOLv2-syn"), {}).get("psnr")
        rows.append([label, res.get((m, "LOLv1"), {}).get("psnr"), res.get((m, "LOLv1"), {}).get("ssim"),
                     res.get((m, "LOLv1"), {}).get("lpips"), dark.get((m, "LOLv1"), {}).get("dark_psnr"),
                     dark.get((m, "LOLv1"), {}).get("dark_ssim"), syn,
                     sum(n) / 3 if all(v is not None for v in n) else None,
                     det.get((ABL_DET[m],), {}).get("mAP50")])
    out += ["## 3. Ablation — fine-tuning from the released LOL-v1 weights (same data order, iterations, LR)", "",
            "Only the loss differs between A-D. Differences below ~0.1-0.2 dB on LOL-v1 (15 images) are within noise. "
            "LOLv2-syn: all rows use LOL-v1 weights (cross-dataset), incl. the start point. "
            "Detection rows were all run on one Kaggle T4 (raw on that GPU: see table 4).", "",
            table(hdr, rows, ["psnr", "ssim", "lpips", "dark_psnr", "dark_ssim", "psnr", "niqe", "mAP50"],
                  ["{:.2f}", "{:.3f}", "{:.3f}", "{:.2f}", "{:.3f}", "{:.2f}", "{:.3f}", "{:.3f}"]), ""]

    # 4. detection
    names = {"raw": "Raw (dark)", "zerodce": "Zero-DCE", "sci": "SCI", "retinexformer": "Retinexformer", "gsad": "GSAD"}
    out += ["## 4. Detection — YOLOv8m (COCO-pretrained, no fine-tuning) on ExDark test split", ""]
    for suffix, title in [("", "1,200 images (CPU)"), ("_200", "200-image subset incl. GSAD (CPU)"),
                          ("_200gpu", "200-image subset, Kaggle T4 (fine-tuning runs)")]:
        keys = [k[0] for k in det if (k[0].endswith(suffix) and (suffix or "_200" not in k[0]))]
        if not keys:
            continue
        rows = []
        for k in keys:
            base = k[: -len(suffix)] if suffix else k
            label = names.get(base, dict((v, a) for a, v in ABL_DET.items()).get(k, base))
            rows.append([label, det[(k,)]["mAP50"], det[(k,)]["mAP50-95"], det[(k,)]["precision"], det[(k,)]["recall"]])
        rows.sort(key=lambda r: -float(r[1]))
        out += [f"**{title}**", "", table(["Input to YOLO", "mAP50↑", "mAP50-95↑", "Precision", "Recall↑"], rows,
                                          ["mAP50", "mAP50-95", None, "mAP50"], ["{:.3f}"] * 4), ""]

    # 5. efficiency
    rows = sorted([[k[0], v["params_M"], v["ms_per_image"], v["image_size"]] for k, v in speed.items()],
                  key=lambda r: float(r[2]))                       # fastest first
    out += ["## 5. Efficiency — one Tesla T4, network time only (GPU-synchronised, first image skipped)", "",
            "| Method | Params (M) | ms / image | Image size |", "|---|---|---|---|"]
    for r in rows:
        pm = f"{float(r[1]):.4f}".rstrip("0").rstrip(".") if r[1] and float(r[1]) < 0.1 else (f"{float(r[1]):.2f}" if r[1] else "–")
        out.append(f"| {r[0]} | {pm} | {float(r[2]):,.1f} | {r[3]} |")
    out.append("")

    (R / "tables.md").write_text("\n".join(out))
    print(f"wrote {R / 'tables.md'} ({len(out)} lines)")


if __name__ == "__main__":
    main()
